name: "Test"
on:
  pull_request:
  push:
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: git submodule update --init --recursive --depth 1
    - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
    - run: cachix use simula
    - run: nix-build -Q default.nix --arg onNixOS "false" --arg devBuild "false" || nix log /nix/store/jp88g1n58jmjbwp5x0522fcmdb003v0w-godot-3.2.drv
    #- run: nix bundle --bundler github:ralismark/nix-appimage --file default.nix --arg onNixOS "false" --arg devBuild "false" -o appimage
    #- uses: actions/upload-artifact@v4
    #  with:
    #    name: my-artifact
    #    path: appimage
    #    overwrite: true