name: "Test"
on:
  pull_request:
  push:
env:
  NIXPKGS_ALLOW_UNFREE: 1
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - run: nix-env -iA cachix -f https://cachix.org/api/v1/install
    - run: cachix use simula
    - run: nix-build -Q default.nix --arg devBuild "false"